---
title: "Status of Women Empowerment in India"
author: "Project -  CS 595 \n by, Ode Deepkumar Rameshbhai (204161011)"
date: "4/14/2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.width= 7, fig.height = 8)
```


## Setup Code Cell  

```{r}

rm(list=ls())  # Clear workspace.

###--PLEASE COMMENT ALL THESE LINES AFTER RUNNING THIS CELL ONCE.--###
## If you're getting errors while installing packages, please have a look at README.

## These are commonly used packages, please comment these if you've them already installed.

# install.packages("dplyr")
# install.packages("ggplot2")
# install.packages("tidyr")
# 
# 
# ## These are packages used in this project, you can comment them to prevent installations.
# 
# install.packages("readxl")  # This is fastest library with .xls or .xlsx files.
# install.packages("cowplot")  # Arrange plots side by side.
# install.packages("treemap") # Treemap
# install.packages("GGally") 
# install.packages("waffle", repos = "https://cinc.rud.is")  # CRAN version is outdated and is not integrabble with other gglayers.
# install.packages("rgeos")
# install.packages("sf")
# install.packages("viridis")


## Shape files


# These 2 lines downloads and unzips shape file used for Indian map. You need
# to run these lines only once, after which you can uncomment these 2 lines.
# This will create 24 or so files in the folder in which this data is placed.
# Not all of them are required, however.

# download.file("http://biogeo.ucdavis.edu/data/diva/adm/IND_adm.zip", destfile = "IND_adm.zip")
# unzip("IND_adm.zip", overwrite = TRUE)


packageVersion("waffle")  # Should be 1.0.1
```

```{r}
library("readxl") 
library("dplyr")
library("ggplot2")
library("tidyr")
library("cowplot")
library("treemap")
library("GGally")
library("waffle")
library("rgeos")
library("sf")
library("viridis")
```


```{r}
theme_global <- function () { 
  theme_minimal(base_size = 10) %+replace% 
   theme(axis.title = element_text(size = 10, face = "bold"),
         axis.text.x = element_text(size = 9),
         axis.text.y = element_text(size = 9),
          plot.title = element_text(size = 12, hjust = 0.5, margin = margin(10, 0, 10, 0)),
          plot.subtitle = element_text(hjust = 0.5)
      )
}

#theme_set(theme_global())
```


```{r}
df_ed_base <-read_excel("ed_level_above_7.xlsx", range = cell_limits(c(8, 4), c(NA, NA)),
          col_names = c("State", "demoRegion", "AgeGroup", "tot", "tot_m", "tot_f",
                        "illit", "illit_m", "illit_f", "lit", "lit_m", "lit_f",
                       "lit_wo_ed", "lit_wo_ed_m", "lit_wo_ed_f", "below_pri", "below_pri_m", "below_pri_f",
                        "pri", "pri_m", "pri_f", "sec", "sec_m", "sec_f", "hsec", "hsec_m", "hsec_f",
                       "ntech_dip", "ntech_dip_m", "ntech_dip_f", "tech_dip", "tech_dip_m", "tech_dip_f",
                        "grad", "grad_m", "grad_f", "ab_grad", "ab_grad_m", "ab_grad_f", "uncls", "uncls_m", "uncls_f"))

western_states = c("State - MAHARASHTRA", "State - GUJARAT", "State - GOA", "State - DAMAN & DIU", "State - DADRA & NAGAR HAVELI")
northern_states = c("State - HIMACHAL PRADESH", "State - UTTAR PRADESH", "State - UTTARAKHAND", "State - PUNJAB", "State - HARYANA", "State - JAMMU & KASHMIR", "State - RAJASTHAN", "State - NCT OF DELHI", "State - CHANDIGARH")
northeastern_states = c("State - ASSAM", "State - MEGHALAYA", "State - MANIPUR", "State - MIZORAM", "State - NAGALAND", "State - TRIPURA", "State - SIKKIM", "State - ARUNACHAL PRADESH")
eastern_states = c("State - ODISHA", "State - BIHAR", "State - WEST BENGAL", "State - JHARKHAND")
southern_states = c("State - LAKSHADWEEP", "State - KARNATAKA", "State - ANDHRA PRADESH", "State - TAMIL NADU", "State - KERALA", "State - PUDUCHERRY", "State - ANDAMAN & NICOBAR ISLANDS")
central_states = c("State - MADHYA PRADESH", "State - CHHATTISGARH")


df_ed_base = df_ed_base %>% mutate(Region = ifelse(State %in% western_states,"Western",
                                    ifelse(State %in% northern_states,"Northern",
                                    ifelse(State %in% northeastern_states,"NorthEastern",
                                    ifelse(State %in% eastern_states,"Eastern",
                                    ifelse(State %in% southern_states,"Southern",
                                    ifelse(State %in% central_states,"Central", NA)))))))
```


```{r}
df_eco_base <-read_excel("workers.xls", range = cell_limits(c(9, 4), c(NA, NA)))

df_eco_base <- df_eco_base %>% select(c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 19, 20, 21))
names(df_eco_base) <- c("State", "demoRegion", "AgeGroup", "pop", "pop_m", "pop_f", "main", "main_m", "main_f", 
                   "marginal1", "marginal1_m", "marginal1_f", "marginal2", "marginal2_m", "marginal2_f", 
                   "non", "non_m", "non_f")

df_eco_base$State = substr(df_eco_base$State,1,nchar(df_eco_base$State)-5)
western_states = c("State - MAHARASHTRA", "State - GUJARAT", "State - GOA", "State - DAMAN & DIU", "State - DADRA & NAGAR HAVELI")
northern_states = c("State - CHANDIGARH", "State - HIMACHAL PRADESH", "State - UTTAR PRADESH", "State - UTTARAKHAND", "State - PUNJAB", "State - HARYANA", "State - JAMMU & KASHMIR", "State - RAJASTHAN", "State - NCT OF DELHI")
northeastern_states = c("State - ASSAM", "State - MEGHALAYA", "State - MANIPUR", "State - MIZORAM", "State - NAGALAND", "State - TRIPURA", "State - SIKKIM", "State - ARUNACHAL PRADESH")
eastern_states = c("State - ODISHA", "State - BIHAR", "State - WEST BENGAL", "State - JHARKHAND")
southern_states = c("State - LAKSHADWEEP", "State - KARNATAKA", "State - ANDHRA PRADESH", "State - TAMIL NADU", "State - KERALA", "State - PUDUCHERRY", "State - ANDAMAN & NICOBAR ISLANDS")
central_states = c("State - MADHYA PRADESH", "State - CHHATTISGARH")

df_eco_base = df_eco_base %>% mutate(Region = ifelse(State %in% western_states,"Western",
                                    ifelse(State %in% northern_states,"Northern",
                                    ifelse(State %in% northeastern_states,"NorthEastern",
                                    ifelse(State %in% eastern_states,"Eastern",
                                    ifelse(State %in% southern_states,"Southern",
                                    ifelse(State %in% central_states,"Central", NA)))))))

df_eco_base$State <- lapply(df_eco_base$State, function(s) paste(substring(s, 9, 9), tolower(substring(s, 10, nchar(s))), sep=''))

selected_states = c("Maharashtra", "Karnataka", "Nct of delhi", "Uttar pradesh", "Andhra Pradesh", "Assam", "West bengal", "Madhya pradesh", "Lakshadweep", "Rajasthan")

df_eco <- df_eco_base %>% filter(demoRegion=="Total", AgeGroup=="15-59") %>% mutate(
    marginal = marginal1 + marginal2,
    marginal_m = marginal1_m + marginal2_m,
    marginal_f = marginal1_f + marginal2_f,
    .keep = "unused") %>% filter
df_eco$State[1] = "India"

df_eco$State = unlist(df_eco$State)
```


```{r}
df_pop_base <- df_ed_base %>% filter(demoRegion == "Total", AgeGroup == "All ages") %>% select(State, Region, tot, tot_m, tot_f)
df_pop_base$State <- unlist(lapply(df_pop_base$State, function(s) paste(substr(s, 9, 9), tolower(substr(s, 10, nchar(s))), sep = "")))
df_pop <- read.csv("pop_growth.csv")
names(df_pop) <- c("Cat", "State", "pop", "pop_growth_rate", "pop_density")
df_pop$State <- unlist(lapply(df_pop$State, function (s) paste(substr(s, 1, 1), tolower(substr(s, 2, nchar(s))), sep = "")))
df_pop_base2 <- df_pop_base
df_pop_base2[df_pop_base2$State == "Nct of delhi", "State"] = "Delhi"
df_pop[df_pop$State == "Andaman & nicobar island", "State"] = "Andaman & nicobar islands"
df_pop <- left_join(df_pop, df_pop_base2)
# a_gRate = ac - ao/ ao, t_gRate = tc - to/ to
# combined_gRate = ac + tc - ao - to/ ao + to
ap_prev_pop = df_pop[2, 3]/(df_pop[2, 4] + 1)
tel_prev_pop = df_pop[2, 3]/(df_pop[2, 4] + 1)
df_pop[2, 3] = df_pop[26, 3] + df_pop[2, 3]
df_pop[2, 4] = (df_pop[2, 3] + df_pop[26, 3] - (ap_prev_pop + tel_prev_pop))/(df_pop[2, 3] + df_pop[26, 3])
df_pop <- df_pop %>% filter(State != "Telangana")
```
```{r}
df_pop$State
```


```{r}
india <- read_sf(dsn = getwd(), "IND_adm3")
indiaF <- fortify(india, region = "ID_1")
```

```{r}
df_eco[df_eco$State == "Nct of delhi", ] <- df_eco %>% filter(State == "Nct of delhi") %>% mutate(State = "Delhi")
states <- df_pop %>% select(State, Region, tot, tot_m, tot_f) %>% filter(State != "India") %>% select(State) %>% arrange(State)
gender_ratio <- df_pop %>% select(State, Region, tot, tot_m, tot_f) %>% filter(State != "India") %>% select(State, tot_m, tot_f) %>% mutate(gr = 1000*tot_f/tot_m) %>% arrange(State) %>% select(gr)
w_emp_rate <- df_eco %>% select(State, pop_f, main_f, marginal_f, non_f) %>% filter(State != "India") %>% arrange(State) %>% mutate(w_emp_rate = (main_f + marginal_f)/pop_f) %>% select(w_emp_rate)
indiaF$ID_1 = unlist(lapply(indiaF$ID_1, function(i) ifelse(i < 32, i, ifelse(i == 32, 2, i-1))))
indiaF$State = unlist(lapply(indiaF$ID_1, function (id) states[id,]))
indiaF$w_emp_rate = unlist(lapply(indiaF$ID_1, function (id) w_emp_rate[id,]))
indiaF$gender_ratio = unlist(lapply(indiaF$ID_1, function (id) gender_ratio[id,]))
```

```{r}
data.frame(states, gender_ratio)
```

```{r}
indiaF %>% ggplot() +
    geom_sf(aes(group = ID_1, fill = gender_ratio), color = NA) +
    labs(title = "Gender Ratio in India", caption = "Source : Census of India, 2011") +
    scale_fill_gradient2(midpoint = 1000, low = "blue", mid = "mintcream", high = "violetred3", name = "Gender Ratio") +
    theme_void() +  theme(axis.title = element_text(face = "bold"),
          plot.title = element_text(face = "bold",
                                    size = 12, hjust = 0.5, margin = margin(10, 0, 10, 0)),
      )
```


```{r}
dir.create(file.path(getwd(), "images"), showWarnings = FALSE)
ggsave("images/1.png")
df_ed <- data.frame(df_ed_base %>% filter(AgeGroup == "All ages", demoRegion == "Total") %>% group_by(State, Region) %>%
summarise_at(vars(-group_cols(), -"demoRegion", -"AgeGroup"), sum))

df_ed$State <- lapply(df_ed$State, function(s) paste(substring(s, 9, 9), tolower(substring(substring(s, 9), 2)), sep=''))
df_ed$State[1] = "India"
```

```{r}
df_ed_plt1 <- df_ed %>% mutate(
                lit_rate = lit/tot,
                lit_rate_m = lit_m/tot_m,
                lit_rate_f = lit_f/tot_f,
                mycolor = ifelse(lit_rate_f > 0.5597068, "black", "red")) %>%
    arrange(lit_rate_f) %>%
    mutate(State=factor(State, levels=State)) 

 
font_face <- ifelse(df_ed_plt1$State == "India", yes = "bold", no = "plain")
font_size <- ifelse(df_ed_plt1$State == "India", yes = 11, no = 9)

df_ed_plt1 %>%
    ggplot( aes(x=State, y=100*lit_rate_f)) +
    geom_segment(aes(xend=State, yend=0, color = mycolor)) +
    scale_color_manual(breaks = c("red", "black"), values = c("darkred", "black")) +
    geom_point(color = "maroon1", size=4) +
    geom_label( aes(fill = font_face),
        label= paste(round(100*(df_ed_plt1$lit_rate_f)), "%"),
        nudge_x = 0.0, nudge_y = 20, 
        check_overlap = T
    ) + 
    scale_fill_manual(values = c("maroon1", "white"), labels = NULL) +
    guides(fill = FALSE, color = FALSE) + 
    coord_flip() +
    labs(title = "Female literacy rate in Indian states",
         x = "State", y = "Female literacy rate (%)",
         caption = "Source : Indian Census, 2011") +
    theme_global() + theme(axis.text.y = element_text(face = font_face, size = font_size))
    
```


```{r}
ggsave("images/2.png")
df_ed_regional <- data.frame(df_ed_base %>% filter(AgeGroup == "All ages", demoRegion == "Total") %>% group_by(Region) %>%
                    filter(!is.na(Region)) %>% summarise_at(vars(-group_cols(), -"State", -"demoRegion", -"AgeGroup"), 
                    sum))
```


```{r fig.height=5, fig.width=6}
df_ed_regional %>% mutate(
                lit_rate = 100*lit/tot,
                lit_rate_m = 100*lit_m/tot_m,
                lit_rate_f = 100*lit_f/tot_f) %>%
    arrange(desc(lit_rate_f)) %>%
    mutate(Region=factor(Region, levels=Region)) %>%   # This trick update the factor levels
    ggplot(aes(x = Region, y = lit_rate_f, fill = Region)) +
    geom_col() +
    scale_fill_viridis_d() + 
    geom_text(aes(y = 30, label = Region), angle=90, colour = "white", fontface="bold") +
    guides(fill = FALSE) + 
    labs(title = "Regional female literacy rate in India",
         y = "Female literacy rate (%)",
         caption = "Source : Indian Census, 2011") +
    theme_global() + theme(axis.text.x =element_blank())
```

```{r fig.width=9, fig.height=6}
ggsave("images/3.png")
df_ed %>% filter (State != "India") %>% mutate(
                lit_rate = 100*lit/tot,
                lit_rate_m = 100*lit_m/tot_m,
                lit_rate_f = 100*lit_f/tot_f,
                lit_rate_gend_diff = lit_rate_f - lit_rate_m) %>%
    arrange(lit_rate_gend_diff) %>%
    mutate(State=factor(State, levels=State)) %>%   # This trick update the factor levels
    ggplot(aes(x=State, y=-lit_rate_gend_diff)) +
    geom_segment(aes(xend=State, yend=0), color="black") +
    geom_point(color = "red", size=4) +
    scale_y_continuous(trans="reverse") +
    theme_global() +
    labs(title = "Gender wise Difference in Literacy Rates",
         x = "State", y = "Male lit. rate - Female lit. rate",
         caption = "Source : Census of India, 2011") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


```{r}
ggsave("images/4.png")
df_lit_national <- read_excel("lit_rate_national.xlsx")
df_lit_national %>% pivot_longer(!Year, names_to = "Gender", values_to = "lit_rate") %>% filter(Gender == "Male") %>%
ggplot(aes(x = Year, y = lit_rate, color = Gender)) + geom_line() + geom_point() +
geom_line(data = df_lit_national %>% pivot_longer(!Year, names_to = "Gender", values_to = "lit_rate") %>% filter(Gender == "Female"), 
       aes(x = Year, y = lit_rate, color = Gender), alpha = 0.9) + geom_point(data = df_lit_national %>% pivot_longer(!Year, names_to = "Gender", values_to = "lit_rate") %>% filter(Gender == "Female"), 
       aes(x = Year, y = lit_rate, color = Gender)) + 
  scale_x_discrete(limits=c(1881, 1891, 1901, 1911, 1921, 1931, 1941, 1951, 1961, 1971, 1981, 1991, 2001, 2011)) +
  labs(title = "Decadal growth in literacy rate of India - Gender wise", subtitle = "From 1881 to 2011", y = "Literacy Rate (%)",
       caption = "Source : Wikipedia") + 
  geom_point(aes(x = 1947, y = 0), color = "orange") +
  geom_segment(aes(x = 1947, xend = 1947, y = 45, yend = 0), lineend = 'round', color = "orange", arrow = arrow(length = unit(0.1, "inches"))) +
  geom_label(aes(x = 1947, y = 45, label = "Indepedence"), colour = "orange", fill = "white") +
  scale_color_manual(values=c("deeppink", "dodgerblue")) +
  theme_global() 
```


```{r fig.height = 4, fig.width=7}
ggsave("images/5.png")
df_ed_youth <- data.frame(df_ed_base %>% filter(AgeGroup %in% c("18", "19", "20-24", "25-29"), demoRegion == "Total") %>% group_by(State) %>%
summarise_at(vars(-group_cols(), -"Region", -"demoRegion", -"AgeGroup"), sum))

df_ed_youth$State <- unlist(lapply(df_ed$State, function(s) paste(substring(s, 1, 1), tolower(substring(s, 2, nchar(s))), sep='')))
df_ed_youth$State[1] = "India"

df_ed_national <- df_ed_youth %>% filter (State == "India") %>% summarise(
    sec_below_m = 100*(lit_wo_ed_m + below_pri_m + pri_m + sec_m + uncls_m)/(lit_wo_ed + below_pri + pri + sec + uncls),
    hsec_eq_m = 100*(hsec_m + ntech_dip_m + tech_dip_m)/(hsec + ntech_dip + tech_dip),
    grad_above_m = 100*(grad_m + ab_grad_m)/(grad + ab_grad),
    
    sec_below_f = 100*(lit_wo_ed_f + below_pri_f + pri_f + sec_f + uncls_f)/(lit_wo_ed + below_pri + pri + sec + uncls),
    hsec_eq_f = 100*(hsec_f + ntech_dip_f + tech_dip_f)/(hsec + ntech_dip + tech_dip),
    grad_above_f = 100*(grad_f + ab_grad_f)/(grad + ab_grad)
    )

data.frame(gender = c("Female", "Male"),
           grad_above = c(df_ed_national$grad_above_f, df_ed_national$grad_above_m),
           hsec_eq = c(df_ed_national$hsec_eq_f, df_ed_national$hsec_eq_m),
           sec_below = c(df_ed_national$sec_below_f, df_ed_national$sec_below_m)) %>%
                      pivot_longer(!gender, names_to = "highest_ed", values_to = "perc") %>%
                      ggplot() + 
                      geom_col(aes(x = highest_ed, y = perc, fill = gender), width = 0.4) +
                      scale_fill_manual(values=c("deeppink", "dodgerblue3")) +
                      scale_x_discrete(labels=c("Graduation & Above", "Higher Secondary (Or Eq.)", "Secondary & Below")) +
                      labs(title = "Gender wise Enrollement at Various Education Levels",
                           subtitle = "Age : 18 - 29 years",
                           y = "Percentage", x = "Education Level", caption = "Source : Census of India, 2011",
                           legend = "Gender") +
                      guides(fill=guide_legend(title = "Gender")) +
                      coord_flip() +
                      theme_global()
                      
                      

```


```{r}
ggsave("images/6.png")

df_gdp <- read_excel("gdp.xls", range = "B7:C40",
          col_names = c("State", "GSDP"))
df_gdp$State[10] = "Jammu & Kashmir"

df_gdp$State <- unlist(lapply(df_gdp$State, function(s) paste(substring(s, 1, 2), tolower(substring(s, 3)), sep='')))

df_gdp$State[which(df_gdp$State == 'Delhi')] = "Nct of delhi"
df_gdp$GSDP[which(df_gdp$State == 'Andhra pradesh')] = df_gdp$GSDP[which(df_gdp$State == 'Telangana')] + 
                              df_gdp$GSDP[which(df_gdp$State == 'Andhra pradesh')] 
df_gdp$State[33] = df_gdp$State[34]
df_gdp$GSDP[33] = df_gdp$GSDP[34]
df_gdp <- df_gdp[-c(34, which(df_gdp$State == "Telangana")),]
df_ed$State <- unlist(df_ed$State)
```


```{r fig.height=6, fig.width=6}
left_join(df_gdp %>% filter(State != "India"), df_ed %>% select(State, tot, tot_m, tot_f, lit_f) %>% 
          left_join(df_eco %>% select(State, Region))) %>% filter(!is.na(Region)) %>%
    ggplot() +
    labs(title = "Relation between GDP & female literacy rate",
         x = "Female Literacy Rate (%)",
         y = "GDP per capita (in lac Rupees)",
         caption = "Sources : (i) : Ministry of Statistics & Programme Implementation, Government of India \n (ii) : Census of India, 2011") +
    geom_point(aes(x = 100*lit_f/tot_f, y = 100*GSDP/tot, fill = Region), shape = 21, size = 3.5) + theme_global()
```

```{r}
ggsave("images/7.png")


df_eco_national <- df_eco %>% filter(State=="India")

df_eco_temp1 <- data.frame(gender=c("Female", "Male"),
                          category = c("Main Workers", "Marginal Workers", "Unemployed",
                                      "Main Workers", "Marginal Workers", "Unemployed"),
                        perc = c(df_eco_national$main_f/df_eco_national$pop_f, 
                                df_eco_national$marginal_f/df_eco_national$pop_f,
                                df_eco_national$non_f/df_eco_national$pop_f,
                                df_eco_national$main_m/df_eco_national$pop_m, 
                                df_eco_national$marginal_m/df_eco_national$pop_m,
                                df_eco_national$non_m/df_eco_national$pop_m))


p1 <- df_eco_temp1 %>% filter(gender == "Female") %>% 
                        mutate(ymax = cumsum(perc),
                        ymin = c(0, head(ymax, n = -1)),
                        labelPosition = (ymax + ymin) / 2,
                        label = paste0(category, ":\n", round(perc*100,2), "%")) %>%
    ggplot(aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=category)) +
     geom_rect() +
     geom_label( x=3.5, aes(y=labelPosition, label=label), color = "black", size=3.5) +
     scale_fill_manual(values = c("deeppink2", "lightpink", "gray")) +
  scale_color_manual(values = c("deeppink2", "hotpink3", "plum3")) +
  coord_polar(theta="y") +
  xlim(c(2, 4)) +
  theme_void() +
  theme(legend.position = "none", plot.margin = unit(c(0, 0, 0, 0), "cm"))

p2 <- df_eco_temp1 %>% filter(gender == "Male") %>%
                        mutate(ymax = cumsum(perc),
                        ymin = c(0, head(ymax, n = -1)),
                        labelPosition = (ymax + ymin) / 2,
                        label = paste0(category, ":\n", round(perc*100,2), "%")) %>%
    ggplot(aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=category)) +
     geom_rect() +
     geom_label( x=3.5, aes(y=labelPosition, label=label), color = "white", size=3.5) +
     scale_fill_manual(values = c("darkblue", "dodgerblue3", "gray")) +
     scale_color_manual(values = c("darkblue", "dodgerblue3", "deepskyblue")) +
    coord_polar(theta="y") + # Try to remove that to understand how the chart is built initially
     xlim(c(2, 4)) + # Try to remove that to see how to make a pie chart
      theme_void() +
      theme(legend.position = "none", plot.margin = unit(c(0, 0, 0, 0), "cm")) +
      labs(caption = "Age : 15-60 years \nSource : Census of India, 2011")

plot_grid(p1, p2, labels = c("Female", "Male"), ncol = 2, vjust = 15)

```


```{r}
ggsave("images/8.png")

indiaF %>% ggplot() +
    geom_sf(aes(group = ID_1, fill = w_emp_rate), color = NA) +
    scale_fill_distiller(palette = "RdPu",trans = "reverse") + theme_void() +
    labs(title = "Women Employment Rate in various Indian states", caption = "Age : 15-60 years \nSource : Census of India, 2011") +
    guides(fill = guide_legend("Women Employment Rate")) 
```

```{r}
ggsave("images/9.png")

df_eco %>% filter(State != "India") %>% 
            mutate(unemp_f = 100*non_f/pop_f) %>% 
                ggplot() +
                geom_boxplot(aes(x = Region, y = unemp_f, fill = Region)) +
                geom_point(aes(x = Region, y = unemp_f, fill = Region), size = 3.5, shape = 21, color = "black") +
                theme_global() +
                labs(title = "Region wise distribution of women unemployment rate", 
                     x = "Region",
                     y = "Unemployment rate (%)",
                     caption = "Age : 15-60 years \nSource : Census of India, 2011") +
                scale_fill_viridis_d()

```


```{r}
ggsave("images/10.png")


left_join(df_gdp %>% mutate(State = ifelse(State == "Nct of delhi", "Delhi", State)), df_eco %>% select(State, pop, pop_m, pop_f, main_f, marginal_f) %>% 
          left_join(df_eco %>% select(State, Region))) %>%
    ggplot() +
    geom_point(aes(x = 100*(main_f + marginal_f)/pop_f, y = 100*GSDP/pop, fill = Region), shape = 21, size = 3.5) + theme_global() +
    geom_smooth(aes(x = 100*(main_f + marginal_f)/pop_f, y = 100*GSDP/pop), level = 0.8) +
    labs(title = "Women unemployment is higher in richer states!",
         x = "Employment Rate (%)",
         y = "GDP per capita (in lac Rupees)",
        caption = "Sources : (i) : Ministry of Statistics & Programme Implementation, Government of India \n (ii) : Census of India, 2011")
```


```{r}
ggsave("images/11.png")


df_f_workers_national <- data.frame(read_excel("f_workers.xlsx", range = cell_limits(c(7, 3), c(NA, NA))) %>% select(c(1:25)))
names(df_f_workers_national) <- c("State", "demoRegion", "class", "maritalStatus", "f_emp", "f_emp_cls", "cultivators", "agri_lab", "agri_allied", "mining", "manufacturing_hhi", "manufacturing_nhhi", "electricity_gas_water", "construction", "wholesale_and_retail_hhi", "wholesale_and_retail_nhhi", "transportation_storage", "accomodation_food_services", "info_comm_hhi", "info_comm_nhhi", "fin_estate_professional", "admin", "ed_social", "arts_other_service_hhi", "arts_other_service_nhhi")
df_f_workers_national <- df_f_workers_national %>% filter(State == "INDIA", class == "Total female workers", maritalStatus == "Total")
df_f_workers_national <- df_f_workers_national %>% mutate(
    agri_and_allied = agri_lab + cultivators + agri_allied,
    arts_other_service = arts_other_service_nhhi + arts_other_service_hhi,
    ed_social = ed_social,
    manufacturing = manufacturing_nhhi + manufacturing_hhi,
    others = mining + electricity_gas_water + construction + wholesale_and_retail_hhi + wholesale_and_retail_nhhi + transportation_storage + accomodation_food_services + info_comm_hhi + info_comm_nhhi + fin_estate_professional + admin, .keep = "unused")

waffle1 <- df_f_workers_national %>% pivot_longer(!c(State, demoRegion, class, maritalStatus), names_to = "Sector", values_to = "N") %>% select(demoRegion, Sector, N) %>%
filter(demoRegion == "Total") %>% mutate(fraction = as.integer(100*N/149948993)) %>% arrange(desc(fraction)) %>% mutate(cumfrac = as.integer(100*(cumsum(fraction)-2))) %>%
filter(Sector != "f_emp" & Sector != "f_emp_cls") %>% select(Sector, fraction)
waffle1[waffle1$Sector == "others", 2] = 100 + waffle1[waffle1$Sector == "others", 2] - sum(waffle1$fraction)

waffle2 <- df_f_workers_national %>% pivot_longer(!c(State, demoRegion, class, maritalStatus), names_to = "Sector", values_to = "N") %>% select(demoRegion, Sector, N) %>%
filter(demoRegion == "Rural") %>% mutate(fraction = as.integer(100*N/121906079)) %>% arrange(desc(fraction)) %>% mutate(cumfrac = as.integer(100*(cumsum(fraction)-2))) %>%
filter(Sector != "f_emp" & Sector != "f_emp_cls") %>% select(Sector, fraction)
waffle2[waffle2$Sector == "others", 2] = 100 + waffle2[waffle2$Sector == "others", 2] - sum(waffle2$fraction)

waffle3 <- df_f_workers_national %>% pivot_longer(!c(State, demoRegion, class, maritalStatus), names_to = "Sector", values_to = "N") %>% select(demoRegion, Sector, N) %>%
filter(demoRegion == "Urban") %>% mutate(fraction = as.integer(100*N/28042914)) %>% arrange(desc(fraction)) %>% mutate(cumfrac = as.integer(100*(cumsum(fraction)-2))) %>%
filter(Sector != "f_emp" & Sector != "f_emp_cls") %>% select(Sector, fraction)
waffle3[waffle3$Sector == "others", 2] = 100 + waffle3[waffle3$Sector == "others", 2] - sum(waffle3$fraction)

waffle3
```


```{r}
waffle1 %>%
  ggplot(aes(fill = Sector, values = fraction)) +
  geom_waffle(n_rows = 10, size = 1, colour = "gray", flip = TRUE) +
  scale_fill_manual(labels = c("Agriculture & Allied", "Other Services", "Manufacturing", "Others", "Education, Health & Social Services"),
                    values = c("green2", "magenta1", "orangered", "grey40", "dodgerblue2")) + 
  coord_equal() +
  theme_global() +
  theme_enhance_waffle() +
  theme(legend.position = "bottom") +
  labs(title = "Which sectords do Indian women work in? ")

ggsave("images/12.png")


p1 <- waffle2 %>%
  ggplot(aes(fill = Sector, values = fraction)) +
  geom_waffle(n_rows = 10, size = 1, colour = "gray", flip = TRUE) +
  scale_fill_manual(labels = c("Agriculture & Allied", "Other Services, Arts & Paid Household work", "Manufacturing", "Others", "Education, Health & Other Social Services"),
                    values = c("green2", "magenta1", "orangered", "grey40", "dodgerblue2")) + 
  coord_equal() +
  theme_global() +
  theme_enhance_waffle() +
  theme(legend.position = "none")

p2 <- waffle3 %>%
  ggplot(aes(fill = Sector, values = fraction)) +
  geom_waffle(n_rows = 10, size = 1, colour = "gray", flip = TRUE) +
  scale_fill_manual(labels = c("", "", "", "", ""),
                    values = c("green2", "magenta1", "orangered", "grey40", "dodgerblue2")) + 
  coord_equal() +
  theme_global() +
  theme_enhance_waffle()+
  theme(legend.position = "none")

plot_grid(p1, p2, labels = c("Rural", "Urban"), ncol = 2)
ggsave("images/13.png")

```


```{r}
df_f_workers_base <- read_excel("f_workers.xlsx", range = cell_limits(c(7, 3), c(NA, NA)))
df_f_workers_base <- df_f_workers_base %>% select(c(1:9))
names(df_f_workers_base) <- c("State", "demoRegion", "workers", "maritialStatus", "f_emp", "f_emp_cls", "cultivators", "agri_lab", "agri_allied")
df_f_workers_base <- df_f_workers_base %>% filter(workers == "Total female workers", maritialStatus == "Total")

df_f_workers <- df_f_workers_base %>% filter(demoRegion == "Total") %>% mutate(
        f_emp_agri = cultivators+agri_lab+agri_allied)
df_f_workers$State <- unlist(lapply(df_f_workers$State, function(s) paste(substring(s, 9, 9), tolower(substring(substring(s, 9), 2)), sep='')))

                                    
left_join(df_f_workers, left_join(df_gdp, df_pop)) %>% ggplot() + 
    geom_point(aes(y = 100*f_emp_agri/tot_f, x = 100*GSDP/tot, color = "blue")) +
    geom_smooth(aes(y = 100*f_emp_agri/tot_f, x = 100*GSDP/tot, color = "blue"), level = 0.6) +
    geom_point(aes(y = 100*(f_emp - f_emp_agri)/tot_f, x = 100*GSDP/tot, color = "red")) +
    geom_smooth(aes(y = 100*(f_emp - f_emp_agri)/tot_f, x = 100*GSDP/tot, color = "red"), level = 0.6) +
    scale_color_manual(breaks=c("red", "blue"), values=c("deeppink", "dodgerblue"), labels=c("Non-Agriculture Employment Rate (Female)", "Agriculture Employment Rate (Female)")) +
    theme_global() +
    labs(title = "Effect of GDP on Women Employment Rate in Indian states",
         y = "Women Employment Rate",
         x = "GDP per capita - in lac Rupees",
         legend = "",
         caption = "Sources : (i) : Ministry of Statistics & Programme Implementation, Government of India \n (ii) : Census of India, 2011"
         ) +
    theme(legend.position = "bottom")
```

```{r}
ggsave("images/14.png")

df_eco %>% filter(State != "India") %>%
            mutate(unemp_f = 100*non_f/pop_f, unemp_m = 100*non_m/pop_m, unemp_diff = unemp_m - unemp_f) %>%
              arrange(desc(unemp_diff)) %>%
              mutate(State=factor(State, levels=State)) %>%
                select(State, unemp_f, unemp_m, unemp_diff, Region) %>%
                    pivot_longer(!c("State", "Region", "unemp_diff"), names_to = "gender", values_to = "Rate") %>%
                        ggplot(aes(x = Rate, y = State)) + geom_point(aes(col = gender)) +
                              geom_line() + theme_global() +
                                labs(title = "Gender wise differences in Unemployment Rate",
                                     y = "State",
                                     x = "Unemployment Rate",
                                     caption = "Census of India, 2011") + 
                                scale_color_manual(breaks=c("unemp_f", "unemp_m"), values=c("deeppink", "dodgerblue"), labels=c("Female Unemployment Rate", "Male Unemployment Rate"))

```


```{r}
ggsave("images/15.png")

df_ed %>% select(State, tot_f, lit_f) %>% left_join(df_pop %>% select(!Cat)) %>%
  filter(!is.na(Region)) %>%
    ggplot() +
    geom_point(aes(x = 100*lit_f/tot_f, y = pop_growth_rate, fill = Region), shape = 21, size = 3.5) + theme_global() +
    labs(title = "Effect of women education on population growth rate",
         x = "Female Literacy Rate (%)",
         y = "Population Growth Rate (%)",
         lab = "Source : Open Government Data Platform - data.gov.in")
```


```{r}
ggsave("images/16.png")

df_crime <- read_excel("recovered_crime1.xls")
names(df_crime) <- c("State", "Crime", "Cases")
df_crime <- df_crime %>% filter(Crime == "Total Crimes against Women", !(State %in% c("Total (All-India)", "Total (State)", "Total (UTs)"))) %>%
    arrange(State)
temp_state <- df_eco %>% select(State, pop_m, pop_f) %>% filter(State != "India") %>% arrange(State) %>% select(State)
df_crime$State <- c(temp_state$State[1:9], "Nct of delhi", temp_state$State[10:24], temp_state$State[26:35])

df_crime <- left_join(df_crime, df_pop %>% select(State, Region, tot_f)) %>%
            mutate(cases_per_1000 = Cases*1000/tot_f)

df_crime %>% filter(State != "Lakshadweep" & State != "Goa") %>% treemap(index = "State", vSize = "cases_per_1000", vColor = "Region", type = "categorical",
                                                                         title = "Crime cases against women per 1000 women", fontsize.labels=c(12,10),
                                                                         fontcolor.labels = "White")
```

```{r fig.height=6, fig.width=7}
#ggsave("images/17.png")

df_ed_youth_2 <- df_ed_youth %>% select(State, lit_f, tot_f, grad_f, ab_grad_f) %>% filter(State != "Lakshadweep" & State != "Goa")
names(df_ed_youth_2) <- c("State", "lit_f_youth", "tot_f_youth", "grad_f", "ab_grad_f")

df_ed_youth_2 %>% left_join(df_crime) %>% filter(!is.na(Region)) %>%
    ggplot() +
    geom_point(aes(x = cases_per_1000, y = 100*lit_f_youth/tot_f_youth, fill = Region, size = tot_f), shape = 21) + theme_global() +
      scale_size(range = c(1, 10), name="Female Population") +
      labs(title = "Safe environment encourages women education.",
           x = "No. of crimes against women (per thousand women)",
           y = "Female literacy rate among youth (15-29 years).",
           caption = "Source : Open Government Data Platform & Census of India, 2011.") +
      scale_size_continuous(label=function(x){return(paste(round(x/1e7, 2), " Crore"))}, name = "Female Population") +
      guides(fill = guide_legend(override.aes = list(size=4)))
```

```{r fig.height=6, fig.width=7}
ggsave("images/18.png")


df_ed_youth_2 %>% left_join(df_crime) %>% filter(!is.na(Region)) %>%
    ggplot() +
    geom_point(aes(x = cases_per_1000, y = 100*(grad_f + ab_grad_f)/tot_f_youth, fill = Region, size = tot_f), shape = 21) + theme_global() +
      scale_size(range = c(1, 10), name="Female Population") +
      labs(title = "Prevalence of crime can discourage women from higher educatio.",
           x = "No. of crimes against women (per thousand women)",
           y = "At least graduated women among youth - % (15-29 years).",
           caption = "Source : Open Government Data Platform & Census of India, 2011.") +
      scale_size_continuous(label=function(x){return(paste(round(x/1e7, 2), " Crore"))}, name = "Female Population") +
      guides(fill = guide_legend(override.aes = list(size=4)))

```
```{r}
ggsave("images/19.png")

```


